source/game_on/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    get 'signup', to: 'users/registrations#new'
    get 'login', to: 'users/sessions#new'
    post 'login', to: 'users/sessions#create'
    delete 'logout', to: 'users/sessions#destroy'
    get 'users/:id/edit', to: 'users/registrations#edit', :as => :edit_user
    put 'users/:id', to: 'users/registrations#update', :as => :user_update
    delete 'users/:id', to: 'users/registrations#destroy', :as => :user_destroy
    get 'users/typing_dna' => 'typing_dna#new', as: :typing_dna
    post 'users/typing_dna' => 'typing_dna#create'
  end
  devise_for :users, skip: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :favorite_games, only: [:index, :update]
  
  resources :users, only: [:index, :show]

  

  get 'admins' => 'users#admins', as: :admins
  

  # Provide mapping between URLs/HTTP verbs to controller
  resources :games do
    resources :reviews
    
    member do
      put 'like' => 'games#like'
      put 'dislike' => 'games#dislike'
      get :launch
    end

    collection do
      get 'download_loader', to: 'games#download_loader'
      get ':file_name', to: 'games#unity_build_files', file_name: /[A-Za-z0-9_-]{1,50}[.](data|wasm)[.](unityweb|code|framework)[.]{0,1}(unityweb){0,1}/
    end
  end
  
  resources :relationships, only: [:create, :destroy]

  resources :invitefriend, only: [:new]
  resources :contactdev, only: [:new]
  resources :contactadm, only: [:new]

  root to: 'games#index'
end

source/game_on/app/models/user.rb
class User < ApplicationRecord

# Include default devise modules. Others available are:
# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable, :confirmable, :lockable
  devise :omniauthable, omniauth_providers: [:google_oauth2, :github]

  acts_as_voter
  has_many :games, dependent: :destroy
  has_many :reviews

  ROLES = %i[admin moderator player]

  has_many :favorites
  has_many :favorite_games, through: :favorites, source: :favorited, source_type: 'Game'

  
  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :following_relationships, source: :followed
  
  has_many :follower_relationships, foreign_key: :followed_id, class_name: 'Relationship', dependent: :destroy
  has_many :followers, through: :follower_relationships

  def follows?(other_user)
    following.include?(other_user)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).or(where(email: auth.info.email)).first_or_create do |user|
      user.provider ||= auth.provider
      user.uid ||= auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.username = auth.info.name
      user.role ||= :player

    end
  end
end

source/game_on/app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    sign_in(resource)
    after_sign_in_path_for(resource)
  end
end

source/game_on/app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def google_oauth2
    authorize! :create, User
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.provider.blank?
      @user.update(provider: request.env['omniauth.auth'].provider, uid: request.env['omniauth.auth'].uid)
    end

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Google') if is_navigational_format?
    else
      session['devise.google_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join
    end
    
  end

  def github
    authorize! :create, User
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.provider.blank?
      @user.update(provider: request.env['omniauth.auth'].provider, uid: request.env['omniauth.auth'].uid)
    end

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Github') if is_navigational_format?
    else
      session['devise.github_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join
    end
    
  end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

source/game_on/app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  def create
    user = User.where(email: params[:user][:email]).first
    if user && user.provider != nil
      flash[:notice] = "You cannot modify your password, your have to sign in with oauth"
      redirect_to login_path
    else
      super
    end
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  protected

  def after_resetting_password_path_for(resource)
    sign_in(resource)
    games_path
  end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

source/game_on/app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  layout "devise"
  before_action :set_user, only: [:edit, :update, :destroy]
  before_action :configure_account_update_params, only: [:update]
  
  # GET /resource/sign_up
  def new
    authorize! :create, User
    super
  end

  # POST /resource
  def create
    authorize! :create, User
    super
    resource.update role: :player
  end

  # GET /resource/:id/edit
  def edit
    if !can? :assign_role, @user
      authorize! :update, @user
    else
      authorize! :assign_role, @user
    end
    # super
  end

  # PUT /resource/:id
  def update
    if !can? :assign_role, @user
      authorize! :update, @user
    else
      authorize! :assign_role, @user
    end
    old_email = @user.email
    email_changed = @user.email != params[:user][:email]
    is_oauth_account = !@user.provider.blank?

    successfully_updated = if can? :assign_role, @user
      @user.update_without_password account_update_params.except([:current_password, :email, :password, :password_confirmation])
    elsif !is_oauth_account
      @user.update_with_password account_update_params
    else
      @user.update_without_password account_update_params.except(:current_password)
    end
    if !successfully_updated
      render 'edit'
      return
    elsif current_user.role == "admin"
      redirect_to user_path(@user)
    else
      bypass_sign_in @user
      redirect_to root_path
    end
    if email_changed
      key = ENV['KEY'].freeze
      crypt = ActiveSupport::MessageEncryptor.new(key)
      require 'net/http'

      apiKey = ENV["TYPINGDNA_API_KEY"]
      apiSecret = ENV["TYPINGDNA_API_SECRET"]
      id = BCrypt::Engine.hash_secret(old_email, key)
      base_url = 'https://api.typingdna.com/changeuser/%s?'
      newuserid = BCrypt::Engine.hash_secret(params[:user][:email], key)
      uri = URI.parse(base_url%[id])
      http = Net::HTTP.new(uri.host)
      
      request = Net::HTTP::Post.new(uri.request_uri)
      request.set_form_data({'newuserid' => newuserid})
      request.basic_auth apiKey, apiSecret
      
      response = http.request(request)
      
      puts response.body
    end
  end

  # DELETE /resource/:id
  def destroy
    authorize! :destroy, @user
    super


    key = ENV['KEY'].freeze
    crypt = ActiveSupport::MessageEncryptor.new(key)
    require 'net/http'

    apiKey = ENV["TYPINGDNA_API_KEY"]
    apiSecret = ENV["TYPINGDNA_API_SECRET"]
    id = BCrypt::Engine.hash_secret(@user.email, key)
    base_url = 'https://api.typingdna.com/user/%s?'
    
    uri = URI.parse(base_url%[id])
    http = Net::HTTP.new(uri.host)
    
    request = Net::HTTP::Delete.new(uri.request_uri)
    request.basic_auth apiKey, apiSecret
    
    response = http.request(request)
    
    puts response.body
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def set_user
    @user = User.find(params[:id])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: extra_params)
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    if can? :assign_role, @user
      devise_parameter_sanitizer.permit(:account_update, keys: [:role])
    else
      devise_parameter_sanitizer.permit(:account_update, keys: extra_params)
    end
  end

  def extra_params
    [:username]
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

source/game_on/app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]
  skip_before_action :check_for_typing!, only: [:destroy]
  layout "devise"

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
  end
end

source/game_on/app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

source/game_on/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    authorize! :read, User
    @users = User.all
    @online_users = User.where("last_seen_at > ?", 2.minutes.ago)
  end

  def show
    @user = User.find(params[:id])
    authorize! :read, @user
    @online_users = User.where("last_seen_at > ?", 5.minutes.ago)
    render :layout => "devise"
  end

  def admins
    authorize! :read, User
    @admins = User.where(role: "admin")
  end
  
end

source/game_on/app/helpers/users_helper.rb
module UsersHelper
end

source/game_on/app/views/users/admins.html.haml
%h1 Admins

%table#admins
  %thead
    %tr
      %th Username
      %th Email
  %tbody
    - @admins.each do |user|
      %tr
        %td= user.username
        %td= user.email
        %td= link_to 'Show', user, class: "link"
        - if can?(:update, user) || can?(:assign_role, user)
          %td= link_to 'Edit', edit_user_path(user), class: "btn"

= link_to 'Back', :back, class: "link"
= link_to 'Games list', games_path, class: "link"
= link_to 'Contact Admins',new_contactadm_path(:user=>current_user), class: "btn"

source/game_on/app/views/users/index.html.haml
%h1 Users

%table#users
  %thead
    %tr
      %th Username
      %th Email
      %th
      %th
  %tbody
    - @users.each do |user|
      %tr
        %td= user.username
        %td= user.email
        %td= link_to 'Show', user, class: "link"
        - if can?(:update, user) || can?(:assign_role, user)
          %td= link_to 'Edit', edit_user_path(user), class: "btn"
         
  
%br
= link_to 'Admins', admins_path, class: "link"
%p
= link_to 'Games list', games_path, class: "link"

source/game_on/app/views/users/show.html.haml
%h2
  = @user.username
  \-
  = @user.role

%p
  %h3 Username
  %div= @user.username

%p
  %h3 Email
  %div= @user.email

- if can? :follow, @user

  %ul
    - if current_user.follows? @user
      %p you already follow #{@user.username}
    - else
      = link_to "Follow", relationships_path(:followed_id => @user), :method => :post, class: "btn"

- else

  %table
    %thead
      %tr
        %th Following
        %th Status
    %tbody
      - for followed in @user.following
        %tr
          %td
            = h followed.username
            - if can? :unfollow, followed
              = link_to "remove", relationship_path(followed), :method => :delete, class: "btn"
          %td
            - if @online_users.include?(followed)
              .onlinestatus Online
            - else
              .offlinestatus Offline
             
  %table
    %thead
      %tr
        %th Followers

    %tbody
      - for follower in @user.followers
        %tr
          %td= h follower.username

%br

%p= link_to "Find people", users_path, class: "link"
- if (can? :update, @user) || (can? :assign_role, @user)
  = link_to 'Edit', edit_user_path, class: "btn"
- if can? :read_favorites_list, @user
  %p= link_to 'Favorite games', favorite_games_path, class: "link"
= link_to 'HomePage', games_path, class: "link"

source/game_on/app/views/users/typing_new.html.haml
%h2 Prove that you're YOU!
- counter = @counter || 0

= form_tag typing_path(@user), :method => :post, :onSubmit => "return setPattern('#{@user.email}')", autocomplete: :off do
  .field
    = label_tag :text, "Type your email, #{@user.email}, and don't copy-paste it!"
    = text_field_tag :text
    = hidden_field_tag :tp
    
  .actions
    = submit_tag "Send typing info"

:javascript
  var tdna = new TypingDNA();
  tdna.start();
  function setPattern(text) {
    var textToType = text;
    var tp = tdna.getTypingPattern({type: 1, text: textToType});
    var typedText = document.getElementById('text').value;
    var isValid = true;
    
    if (!tp) {
        isvalid = false;
    } 
    if ((typedText.length / textToType.length) < 0.8) {
        isValid = false;
    }
    if (compareTexts(textToType, typedText)<0.8) {
        isValid = false;
    }
    
    if (isValid) {
      document.getElementById('tp').value = tp;
      document.getElementById('counter').value = #{counter};
    }
  }

  function compareTexts (t1, t2) {
    var dt1 = t1.split( ' ' );
    var dt2 = t2.split( ' ' );
    var total2 = 0 ;
    var total1 = 0 ;
    for ( var i in dt2) {
    total2 += (dt1.indexOf(dt2[i]) > -1 ) ? 1 : 0 ;
    }
    for ( var i in dt1) {
    total1 += (dt2.indexOf(dt1[i]) > -1 ) ? 1 : 0 ;
    }
    var total = (dt1.length > dt2.length) ? dt1.length : dt2.length;
    var length = (dt1.length > dt2.length) ? dt1.length : dt2.length;
    return total / length;
  }