source/game_on/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    get 'signup', to: 'users/registrations#new'
    get 'login', to: 'users/sessions#new'
    post 'login', to: 'users/sessions#create'
    delete 'logout', to: 'users/sessions#destroy'
    get 'users/:id/edit', to: 'users/registrations#edit', :as => :edit_user
    put 'users/:id', to: 'users/registrations#update', :as => :user_update
    delete 'users/:id', to: 'users/registrations#destroy', :as => :user_destroy
    get 'users/typing_dna' => 'typing_dna#new', as: :typing_dna
    post 'users/typing_dna' => 'typing_dna#create'
  end
  devise_for :users, skip: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :favorite_games, only: [:index, :update]
  
  resources :users, only: [:index, :show]

  

  get 'admins' => 'users#admins', as: :admins
  

  # Provide mapping between URLs/HTTP verbs to controller
  resources :games do
    resources :reviews
    
    member do
      put 'like' => 'games#like'
      put 'dislike' => 'games#dislike'
      get :launch
    end

    collection do
      get 'download_loader', to: 'games#download_loader'
      get ':file_name', to: 'games#unity_build_files', file_name: /[A-Za-z0-9_-]{1,50}[.](data|wasm)[.](unityweb|code|framework)[.]{0,1}(unityweb){0,1}/
    end
  end
  
  resources :relationships, only: [:create, :destroy]

  resources :invitefriend, only: [:new]
  resources :contactdev, only: [:new]
  resources :contactadm, only: [:new]

  root to: 'games#index'
end

source/game_on/app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  # Enable file attachments
  has_many_attached :files
  
  acts_as_votable
  # Before creating or updating a Game object, check if the title is provided
  validates :title, presence: true

  # Scan files for viruses before saving them
  before_create :scan_for_viruses
  before_update :scan_for_viruses

  CATEGORIES = ["Action", "Adventure", "Casual", "Indie", "Racing", "RPG", "Simulation", "Sports", "Strategy", "Other"]

  SORTING_CRITERIA = {"Alphabetic" => " ORDER BY title",
                      "Newest" => " ORDER BY created_at DESC",
                      "Hottest" => " ORDER BY cached_votes_score DESC",
                      "Controversial" => " ORDER BY IFNULL((CAST((cached_votes_total - ABS(cached_votes_score)) AS FLOAT))/cached_votes_total, 0.0) DESC"}

  validates :category, inclusion: { in: CATEGORIES }

  def input_handler(params)
    # regex taken from semver.org
    semver = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/

    if (!params[:version].empty? && !semver.match?(params[:version]))
      raise ArgumentError, "invalid version number (visit semver.org for reference and examples)"
    end
    if !params[:files].nil? && params[:files].length() != 5
      raise ArgumentError, "provide 0 or 5 files"
    end
  end

  def self.build_file(file_name, game_id)
    if file_name != nil && game_id != nil
      game = Game.find(game_id)
      game.files.each do |file|
        if file.filename == file_name || file_name == "json" && file.filename.to_s.include?(".json")
          return file
        end
      end
    end
    raise IOError
  end
  
  def self.search(search)

    # QUERY:
    #
    # WITH search_query AS (
    #
    #   SELECT *
    #   FROM games
    #   WHERE title LIKE '%#{word_000}%' AND category = '#{search[:category]}'
    #
    #   UNION
    #
    #   SELECT *
    #   FROM games
    #   WHERE title LIKE '%#{word_001}%' AND category = '#{search[:category]}'
    #
    #   UNION
    #
    #   ad libitum... (the number of unions will depend on the number of words in the name searched)
    #
    # )
    #
    # SELECT *
    # FROM search_query
    # ORDER BY ... (sorting criteria)

    query = "WITH search_query AS ("
    if search[:title].empty?
      if search[:category].eql?("Any")
        query += "SELECT * FROM games"
      else
        query += "SELECT * FROM games WHERE category = '#{search[:category]}'"
      end
    else
      words = search[:title].scan(/[\w']+/)
      
      query += "SELECT * FROM games WHERE title LIKE '%#{words[0]}%'"
      
      query += " AND category = '#{search[:category]}'" if !search[:category].eql?("Any")
      
      words.drop(1).each do |word|
        query += " UNION SELECT * FROM games WHERE title LIKE '%#{word}%'"
        query += " AND category = '#{search[:category]}'" if !search[:category].eql?("Any")
      end
    end
    query += ") SELECT * FROM search_query"
    query += SORTING_CRITERIA[search[:sorting_criterion]] if !search[:sorting_criterion].eql?("Any")
    self.find_by_sql(query)
  end

  def favorited_by?(user)
    favorites = user.favorite_games
    !favorites.where(id: self).empty?
  end

  private
  
  def scan_for_viruses
    self.files.each do |file|
      path = ActiveStorage::Blob.service.send(:path_for, file.key)
      unless Clamby.safe?(path)
        File.delete(path)
        raise SecurityError, "A virus has been found on #{file.filename}, upload aborted."
      end
    end
  end

end

source/game_on/app/controllers/games_controller.rb
# This file is app/controllers/games_controller.rb
class GamesController < ApplicationController
  skip_before_action :save_last_url, only: [:like, :dislike]
  skip_before_action :authenticate_user!, only: [:index, :show]
  # before_action :require_permission, only: [:edit, :update, :destroy]
  respond_to do |format|
    format.js
  end
  
  def index
    authorize! :read, Game
    if params[:game].nil?
      @games = Game.all
      @title = nil
      @category = nil
      @sorting_criteria = nil
    else
      @games = Game.search(search_game_params)
      @title = search_game_params[:title]
      @category = search_game_params[:category]
      @sorting_criteria = search_game_params[:sorting_criterion]
    end
  end

  def show
    respond_to do |format|
      format.html { 
        @game = Game.find(params[:id])
        authorize! :read, @game

        @favorite_exists = !(Favorite.where(user: current_user, favorited: @game) == [])
      } # show.html.haml
      format.json { send_build_file "json" }
    end
  end

  def create

    if params[:tp] != ""

      key = ENV['KEY'].freeze
      crypt = ActiveSupport::MessageEncryptor.new(key)

      require 'net/http'
      
      apiKey = ENV["TYPINGDNA_API_KEY"]
      apiSecret = ENV["TYPINGDNA_API_SECRET"]
      id = BCrypt::Engine.hash_secret(current_user.email, key)
      base_url = 'https://api.typingdna.com/%s/%s'
      tp = params[:tp]
      
      uri = URI.parse(base_url%['auto',id])
      http = Net::HTTP.new(uri.host)
      
      request = Net::HTTP::Post.new(uri.request_uri)
      request.set_form_data({'tp' => tp})
      request.basic_auth apiKey, apiSecret
      
      response = http.request(request)
      
      puts response.body
      
      parsed_json = ActiveSupport::JSON.decode(response.body)
      
      if parsed_json["action"] == "verify" && parsed_json["result"] == 0
        current_user.enrolled = false
        current_user.save
        flash[:warning] = "It seems like you're not you..."
        redirect_to typing_dna_path
        return
      end
    end


    @game = Game.new(game_params)
    authorize! :create, Game
    @game.user = current_user

    begin
      @game.input_handler(params[:game])
    rescue ArgumentError => e
      flash[:error] = "Error while creating a new game: " + e.message
      redirect_to games_path
      return
    end

    @game.version = nil if game_params[:version].empty?
    if @game.save
      if @game.files.attached? && !@game.version.nil?
        flash[:notice] = "'#{@game.title}' v:#{@game.version} added successfully"
      elsif @game.files.attached? && @game.version.nil?
        flash[:notice] = "'#{@game.title}' added successfully, no version provided"
      elsif !@game.files.attached? && !@game.version.nil?
        flash[:notice] = "'#{@game.title}' v:#{@game.version} added, no file provided"
      else
        flash[:notice] = "'#{@game.title}' added, no version neither file provided"
      end
      redirect_to games_path
    else
      flash[:error] = @game.errors.full_messages
      redirect_to games_path
    end
    
  end

  def update

    if params[:tp] != ""

      key = ENV['KEY'].freeze
      crypt = ActiveSupport::MessageEncryptor.new(key)

      require 'net/http'
      
      apiKey = ENV["TYPINGDNA_API_KEY"]
      apiSecret = ENV["TYPINGDNA_API_SECRET"]
      id = BCrypt::Engine.hash_secret(current_user.email, key)
      base_url = 'https://api.typingdna.com/%s/%s'
      tp = params[:tp]
      
      uri = URI.parse(base_url%['auto',id])
      http = Net::HTTP.new(uri.host)
      
      request = Net::HTTP::Post.new(uri.request_uri)
      request.set_form_data({'tp' => tp})
      request.basic_auth apiKey, apiSecret
      
      response = http.request(request)
      
      puts response.body
      
      parsed_json = ActiveSupport::JSON.decode(response.body)
      
      if parsed_json["action"] == "verify" && parsed_json["result"] == 0
        current_user.enrolled = false
        current_user.save
        flash[:warning] = "It seems like you're not you..."
        redirect_to typing_dna_path
        return
      end
    end

    @game = Game.find(params[:id])
    authorize! :update, @game

    begin
      @game.input_handler(params[:game])
    rescue ArgumentError => e
      flash[:error] = "Error while creating a new game: " + e.message
      redirect_to games_path
      return
    end

    if !params[:game][:files].nil? && params[:game][:files].length() == 5
        # Delete old files
        @game.files.purge
        # Attach new ones
        @game.files.attach(params[:game][:files])
    end
    if @game.update(edit_game_params)
      if edit_game_params[:version].empty?
        @game.version = nil
        @game.save
      end
      if params[:game][:files].nil?
        flash[:notice] = "'#{@game.title}' updated successfully"
      elsif params[:game][:files].length() == 5 && !@game.version.nil?
        flash[:notice] = "'#{@game.title}' updated successfully, released patch v:#{@game.version}"
      elsif params[:game][:files].length() == 5 && @game.version.nil?
        flash[:notice] = "'#{@game.title}' updated successfully, released new patch"
      else
        flash[:error] = "Error while releasing new patch: provide 5 files"
      end
      redirect_to games_path
    else
      flash[:error] = @game.errors.full_messages
      render 'edit'
    end
    
  end
  
  def new
    authorize! :create, Game
  end

  def edit
    @game = Game.find(params[:id])
    authorize! :update, @game
  end

  def destroy
    @game = Game.find(params[:id])
    authorize! :destroy, @game

    # delete any file attached
    @game.files.purge
    # destroy the game
    @game.destroy
    
    flash[:notice] = "'#{@game.title}' deleted successfully"
    redirect_to games_path
  end

  def launch
    authorize! :play, Game
    cookies.signed[:game] = { value: params[:id], expires: 1.minute }
  end

  def download_loader
    send_build_file "UnityLoader.js"
  end
  
  def unity_build_files
    send_build_file params[:file_name].to_s
  end
  
  def like
    @game = Game.find(params[:id])
    authorize! :vote, @game
    if user_signed_in?
      if !current_user.liked? @game
        if current_user.disliked? @game
          @game.undisliked_by current_user
        end
        @game.liked_by current_user
      else
        @game.unliked_by current_user
      end
    else
      redirect_to login_path # not working...
    end
  end
  
  def dislike
    @game = Game.find(params[:id])
    authorize! :vote, @game
    if user_signed_in?
      if !current_user.disliked? @game
        if current_user.liked? @game
          @game.unliked_by current_user
        end
        @game.disliked_by current_user
      else
        @game.undisliked_by current_user
      end
    else
      redirect_to login_path # not working...
    end
  end
  
  private
    
  def game_params
    params.require(:game).permit(:title, :info, :category, :version, files: [])
  end

  # deprecated because of role model authorization
  def require_permission
    if current_user.id != Game.find(params[:id]).user_id
      flash[:warning] = "You must be the owner of the game to perform this action"
      redirect_to games_path
    end
  end

  def edit_game_params
    params.require(:game).permit(:title, :info, :category, :version)
  end

  def search_game_params
    params.require(:game).permit(:title, :category, :sorting_criterion)
  end

  def send_build_file file_name
    begin
      file = Game.build_file(file_name, cookies.signed[:game])
      send_data file.download, filename: file.filename.to_s, content_type: file.content_type
    rescue IOError => e
      head :no_content # HTTP 204 no content
    end
  end
end


source/game_on/app/views/games/dislike.js.erb
<% if current_user.disliked? @game %>
  $('.dislike-btn').addClass('disliked');
  $('.like-btn').removeClass('liked');
<% else %>
  $('.dislike-btn').removeClass('disliked');
<% end %>
$('.dislikes-count').html('<%= @game.get_dislikes.size %>');
$('.likes-count').html('<%= @game.get_likes.size %>');

source/game_on/app/views/games/edit.html.haml
= link_to 'Back to main menu', games_path, class: "link"
= link_to "Back to #{@game.title}", game_path(@game), class: "link"
%h2 Edit #{@game.title}

= form_tag game_path(@game), :method => :put, :multipart=>true, :onSubmit => "return setPattern()" do

  = label :game, :title, 'Title'
  = text_field :game, :title

  = label :game, :info, 'Info'
  = hidden_field_tag :tp
  = text_area :game, :info

  = label :game, :category, 'Category'
  = select(:game, :category, options_for_select(Game::CATEGORIES, @game.category))

  = label :game, :version, 'Version (For reference and examples on semantic versioning, visit semver.org)'
  = text_field :game, :version, value: @game.version

  = label :game, :files, 'Ready to release a new patch? Upload the files here (Not every file of the build is needed, select just the files in foo/Build/*)'
  = file_field :game, :files, multiple: true

  = submit_tag 'Commit updates'
%br
= link_to 'Delete game', game_path(@game), :method => :delete, class: "btn"

:javascript
    var tdna = new TypingDNA();
    tdna.start();
    function setPattern() {
        var typedText = document.getElementById('game_info').value;
        var tp = tdna.getTypingPattern({type: 0, length: typedText.length});
        var isValid = true;
        
        if (!tp) {
        isvalid = false;
        } 
        if (typedText.length < 100) {
        isValid = false;
        }
        
        if (isValid) {
        document.getElementById('tp').value = tp;
        }
    }

source/game_on/app/views/games/index.html.haml
%h1 Game-on

= form_tag games_path, :method => :get do

  %table
    %td
      = label :game, :title, 'Search by name'
      = text_field :game, :title, :value => @title

    %td
      = label :game, :category, 'Search by category'
      = select(:game, :category, options_for_select(['Any'] + Game::CATEGORIES, @category))

    %td
      = label :game, :sorting_criterion, 'Sorting criterion'
      = select(:game, :sorting_criterion, options_for_select(['Any'] + Game::SORTING_CRITERIA.keys, @sorting_criteria))

    %td= submit_tag 'Search'

    %td= link_to 'Show all', games_path, class: "btn"

%table#games
  %thead
    %tr
      %th Game Title
      %th Info
  %tbody
    - @games.each do |game|
      %tr
        %td= game.title
        %td= link_to "More about #{game.title}", game_path(game), class: "link"


= link_to 'Add new game', new_game_path, class: "btn"
- if can? :read, Favorite
  = link_to 'Favorite games', favorite_games_path, class: "link"

source/game_on/app/views/games/like.js.erb
<% if current_user.liked? @game %>
  $('.like-btn').addClass('liked');
  $('.dislike-btn').removeClass('disliked');
<% else %>
  $('.like-btn').removeClass('liked');
<% end %>
$('.likes-count').html('<%= @game.get_likes.size %>');
$('.dislikes-count').html('<%= @game.get_dislikes.size %>');

source/game_on/app/views/games/new.html.haml
%h2 Create a new game

= form_tag games_path, :method => :post , :multipart=>true, :onSubmit => "return setPattern()" do

    = label :game, :title, 'Title'
    = text_field :game, :title

    = label :game, :info, 'Info'
    = hidden_field_tag :tp
    = text_area :game, :info

    = label :game, :category, 'Category'
    = select(:game, :category, options_for_select(Game::CATEGORIES, 'Other'))

    = label :game, :version, 'Version (For reference and examples on semantic versioning, visit semver.org)'
    = text_field :game, :version

    = label :game, :files, 'Attach build files (Not every file of the build is needed, select just the files in foo/Build/*)'
    = file_field :game, :files, multiple: true
   
    = submit_tag 'Submit game'

= link_to 'Games list', games_path, class: "link"

:javascript
    var tdna = new TypingDNA();
    tdna.start();
    function setPattern() {
        var typedText = document.getElementById('game_info').value;
        var tp = tdna.getTypingPattern({type: 0, length: typedText.length});
        var isValid = true;
        
        if (!tp) {
        isvalid = false;
        } 
        if (typedText.length < 100) {
        isValid = false;
        }
        
        if (isValid) {
        document.getElementById('tp').value = tp;
        }
    }

source/game_on/app/views/games/show.html.haml
%h3= link_to 'Games list', games_path, class: "link"
%h1 #{@game.title}
.row
  .column.left
    - if @game.version != nil
      = link_to "#{User.find(@game.user_id).username}", user_path(@game.user_id), class: "link"
      Version: #{@game.version}
    - if @game.category != 'Other'
      Category: #{@game.category}
  .column.right{:style => "text-align: right"}
    - if can? :update, @game
      = link_to 'Edit game', edit_game_path(@game), class: "btn"
    - if (can?(:destroy, @game) && !can?(:update, @game)) || can?(:manage, @game)
      = link_to 'Delete game', game_path(@game), data: { confirm: "Are you sure?" }, method: :delete, class: "btn"

- if can? :play, @game
  - if @game.files.attached?
    .webgl-content{:id => "webglCanvas", :style => "position: relative; width: 960px; height: 0px"}
      #unityContainer{:style => "width: 960px; height: 600px; background: #202020;"}
        .gameplay{:id => "play_game", :style => "text-align: center; padding-top: 270px"}
          = link_to 'Play', launch_game_path(@game), method: :get, remote: true, id: "play"
      .footer
        .webgl-logo
        .fullscreen{:id => "unity_fullscreen", :style => "visibility: hidden;", :onclick => "unityInstance.SetFullscreen(1)"}
  - else
    %br
    %h4 Work in progress!

  .canvas-placeholder{:style => "width: 0px; height: 650px; position: relative;"}
  %footer{:style => "width: 100%; height: 50px; position: absolute;"}
- else
  %br

  You have to be signed in to play!

.row
  .column.left
    %h3 Description:
    %p#description= @game.info

    %div
      - if can? :vote, @game
        %vote.likes-count= @game.get_likes.size
        - if current_user && current_user.liked?(@game)
          %vote= link_to 'like', like_game_path(@game), method: :put, remote: true, class: 'like-btn liked'
        - else
          %vote= link_to 'like', like_game_path(@game), method: :put, remote: true, class: 'like-btn'
        
        %vote.dislikes-count= @game.get_dislikes.size
        - if current_user && current_user.disliked?(@game)
          %vote= link_to 'dislike', dislike_game_path(@game), method: :put, remote: true, class: 'dislike-btn disliked'
        - else
          %vote= link_to 'dislike', dislike_game_path(@game), method: :put, remote: true, class: 'dislike-btn'
      - if can? :add_to_favorites, @game
        %br= link_to favorite_text, favorite_game_path(game_id: @game), id: 'favorite_link', remote: true, method: :patch, class: "btn"
    - if can? :create, Review
      = link_to 'Add a review', new_game_review_path(@game), class: "btn"
    - if can? :read, Review
      = link_to 'View the reviews', game_reviews_path(@game), class: "link"
    - if can? :contact, @game.user
      %p= link_to 'Report bug to developers', new_contactdev_path(:dev=>@game.user,:game=>@game,:user=>current_user), class: "btn"
  .column.right
    - if can? :play, @game
      %table
        %thead
          %tr
            %th Invite a follower
        %tbody
          - for user in current_user.followers
            - if can? :invite, user
              %tr
                %td
                  = h user.username
                  = link_to 'invite friend', new_invitefriend_path(:friend=> user,:user=>current_user,:game=>@game), class: "btn"
