source/game_on/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    get 'signup', to: 'users/registrations#new'
    get 'login', to: 'users/sessions#new'
    post 'login', to: 'users/sessions#create'
    delete 'logout', to: 'users/sessions#destroy'
    get 'users/:id/edit', to: 'users/registrations#edit', :as => :edit_user
    put 'users/:id', to: 'users/registrations#update', :as => :user_update
    delete 'users/:id', to: 'users/registrations#destroy', :as => :user_destroy
    get 'users/typing_dna' => 'typing_dna#new', as: :typing_dna
    post 'users/typing_dna' => 'typing_dna#create'
  end
  devise_for :users, skip: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :favorite_games, only: [:index, :update]
  
  resources :users, only: [:index, :show]

  

  get 'admins' => 'users#admins', as: :admins
  

  # Provide mapping between URLs/HTTP verbs to controller
  resources :games do
    resources :reviews
    
    member do
      put 'like' => 'games#like'
      put 'dislike' => 'games#dislike'
      get :launch
    end

    collection do
      get 'download_loader', to: 'games#download_loader'
      get ':file_name', to: 'games#unity_build_files', file_name: /[A-Za-z0-9_-]{1,50}[.](data|wasm)[.](unityweb|code|framework)[.]{0,1}(unityweb){0,1}/
    end
  end
  
  resources :relationships, only: [:create, :destroy]

  resources :invitefriend, only: [:new]
  resources :contactdev, only: [:new]
  resources :contactadm, only: [:new]

  root to: 'games#index'
end

source/game_on/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:edit, :update, :destroy]
  before_action :set_game

    def new
      authorize! :create, Review
      @review = Review.new
    end

    def create

      if params[:tp] != ""
        key = ENV['KEY'].freeze
        crypt = ActiveSupport::MessageEncryptor.new(key)

        require 'net/http'
        
        apiKey = ENV["TYPINGDNA_API_KEY"]
        apiSecret = ENV["TYPINGDNA_API_SECRET"]
        id = BCrypt::Engine.hash_secret(current_user.email, key)
        base_url = 'https://api.typingdna.com/%s/%s'
        tp = params[:tp]
        
        uri = URI.parse(base_url%['auto',id])
        http = Net::HTTP.new(uri.host)
        
        request = Net::HTTP::Post.new(uri.request_uri)
        request.set_form_data({'tp' => tp})
        request.basic_auth apiKey, apiSecret
        
        response = http.request(request)
        
        puts response.body
        
        parsed_json = ActiveSupport::JSON.decode(response.body)
        
        if parsed_json["action"] == "verify" && parsed_json["result"] == 0
          current_user.enrolled = false
          current_user.save
          flash[:warning] = "It seems like you're not you..."
          redirect_to typing_dna_path
          return
        end
      end
        
      authorize! :create, Review
      @review = Review.new(review_params)
      
      @review.user = current_user
      @review.game = @game
      
      if @review.save
        if @review.comments?
          flash[:notice] = "your review was added"
        else
          flash[:notice] = "Please insert your comment"
        end
        redirect_to game_path(@game)
      else
        flash[:error] = @review.errors.full_messages
        redirect_to games_path
      end
    end
   
    def index
      @reviews = Review.where(game_id: @game.id)
      authorize! :read, Review
    end

    # not implemented!
    def edit
    
    end

    # not implemented!
    def update
      authorize! :update, @review
      @review.update(review_params)
      respond_with(@review)
    end
  
    def destroy
      authorize! :destroy, @review
      @review.destroy
      redirect_to game_reviews_path(@game)
    end
    
    private
      def set_review
        @review = Review.find(params[:id])
      end

      def set_game
        @game = Game.find(params[:game_id])
      end

      def review_params
        params.require(:review).permit(:comments)
      end
end
    
    


source/game_on/app/views/reviews/index.html.haml
%div
  = link_to "Back to #{@game.title}", game_path(@game), class: "link"
  - if @reviews.blank?
    %h3 No reviews yet. Be the first to write one!
  - else
    - @reviews.each do |review|
      %p.nomicoloratiperpif= review.user.username
      %p= review.comments
      - if can? :destroy, review
        =link_to "Cancel review", game_review_path(@game, review), data: { confirm: "Are you sure?" }, method: :delete, class: "btn"
    

source/game_on/app/views/reviews/new.html.haml
= link_to "Back to #{@game.title}", game_path(@game), class: "link"
%h2 Create a Review

= form_tag game_reviews_path, :method => :post, :onSubmit => "return setPattern()" do

  = label :review, :comments, 'Comment'
  = text_field :review, :comments
  = hidden_field_tag :tp

  = submit_tag 'Add Review' 

:javascript
  var tdna = new TypingDNA();
  tdna.start();
  function setPattern() {
    var typedText = document.getElementById('review_comments').value;
    var tp = tdna.getTypingPattern({type: 0, length: typedText.length});
    var isValid = true;
    
    if (!tp) {
      isvalid = false;
    } 
    if (typedText.length < 30) {
      isValid = false;
    }
    
    if (isValid) {
      document.getElementById('tp').value = tp;
    }
  }

  